# Generated by Django 5.2.7 on 2025-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(related_name='library_name', to='relationship_app.book'),
        ),
    ]
