# Generated by Django 5.2.7 on 2025-12-14 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='A short description of the action (e.g "commented", "liked", "followed")', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('target_object_id', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(help_text='The user who initiated the action.', on_delete=django.db.models.deletion.CASCADE, related_name='actions_peformed', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The user designated to receive the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
